"""esquema inicial: dos mundos

Revision ID: ae306810ae14
Revises: 
Create Date: 2026-06-09 09:01:52.112021
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ae306810ae14'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acciones',
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('glifo', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('categorias',
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('color_accent', sa.String(length=9), nullable=False),
    sa.Column('color_text', sa.String(length=9), nullable=False),
    sa.Column('img', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('tz', sa.String(length=64), nullable=False),
    sa.Column('hora_aviso', sa.String(length=5), nullable=False),
    sa.Column('aviso_activo', sa.Boolean(), nullable=False),
    sa.Column('terminos_aceptados_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firebase_uid')
    )
    op.create_table('cartas',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('categoria_slug', sa.String(length=40), nullable=False),
    sa.Column('accion_slug', sa.String(length=40), nullable=False),
    sa.Column('frase', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['accion_slug'], ['acciones.slug'], ),
    sa.ForeignKeyConstraint(['categoria_slug'], ['categorias.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartas_accion_slug'), 'cartas', ['accion_slug'], unique=False)
    op.create_index(op.f('ix_cartas_categoria_slug'), 'cartas', ['categoria_slug'], unique=False)
    op.create_table('usuario_categorias',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('categoria_slug', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['categoria_slug'], ['categorias.slug'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'categoria_slug')
    )
    op.create_index(op.f('ix_usuario_categorias_usuario_id'), 'usuario_categorias', ['usuario_id'], unique=False)
    op.create_table('entregas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('carta_id', sa.String(length=40), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estrellas', sa.Integer(), nullable=True),
    sa.Column('completada', sa.Boolean(), nullable=False),
    sa.Column('reflexion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['carta_id'], ['cartas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entregas_usuario_id'), 'entregas', ['usuario_id'], unique=False)
    op.create_table('compartidos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('entrega_id', sa.String(length=36), nullable=True),
    sa.Column('carta_id', sa.String(length=40), nullable=False),
    sa.Column('modo', sa.String(length=20), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['carta_id'], ['cartas.id'], ),
    sa.ForeignKeyConstraint(['entrega_id'], ['entregas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compartidos_token'), 'compartidos', ['token'], unique=True)
    op.create_index(op.f('ix_compartidos_usuario_id'), 'compartidos', ['usuario_id'], unique=False)
    op.create_table('fotos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entrega_id', sa.String(length=36), nullable=False),
    sa.Column('storage_path', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entrega_id'], ['entregas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fotos_entrega_id'), 'fotos', ['entrega_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fotos_entrega_id'), table_name='fotos')
    op.drop_table('fotos')
    op.drop_index(op.f('ix_compartidos_usuario_id'), table_name='compartidos')
    op.drop_index(op.f('ix_compartidos_token'), table_name='compartidos')
    op.drop_table('compartidos')
    op.drop_index(op.f('ix_entregas_usuario_id'), table_name='entregas')
    op.drop_table('entregas')
    op.drop_index(op.f('ix_usuario_categorias_usuario_id'), table_name='usuario_categorias')
    op.drop_table('usuario_categorias')
    op.drop_index(op.f('ix_cartas_categoria_slug'), table_name='cartas')
    op.drop_index(op.f('ix_cartas_accion_slug'), table_name='cartas')
    op.drop_table('cartas')
    op.drop_table('usuarios')
    op.drop_table('categorias')
    op.drop_table('acciones')
    # ### end Alembic commands ###
